require 'json'

module VBO
  module SkAgent
    module SkillsLoader
      SKILLS_DIR = File.join(__dir__, 'skills')
      @registry = {} unless defined?(@registry)

      # --- Load All Skills ---

      def self.load_all
        @registry = {}
        return unless File.directory?(SKILLS_DIR)

        Dir.glob(File.join(SKILLS_DIR, '*/manifest.json')).each {|manifest_path|
          load_skill(File.dirname(manifest_path))
        }

        generate_index
        puts "[SkAgent] #{@registry.size} skill(s) loaded: #{@registry.keys.join(', ')}"
      end

      def self.load_skill(skill_dir)
        manifest_path = File.join(skill_dir, 'manifest.json')
        manifest = JSON.parse(File.read(manifest_path))

        name = manifest['name']
        runtime = manifest['runtime'] || 'ruby'
        entry = manifest['entry']

        # Agent-only skills have no Ruby code to load
        if runtime != 'agent' && entry
          entry_path = File.join(skill_dir, entry)
          unless File.exist?(entry_path)
            puts "[SkAgent] WARN: Skill '#{name}' entry not found: #{entry}"
            return
          end

          # Check dependencies (warn only)
          (manifest['dependencies'] || []).each {|dep|
            unless @registry.key?(dep)
              puts "[SkAgent] WARN: Skill '#{name}' depends on '#{dep}' (not loaded)"
            end
          }

          # Load Ruby entry point
          if entry.end_with?('.rbe')
            Sketchup.require entry_path.sub(/\.rbe$/, '')
          else
            require entry_path
          end
        end

        @registry[name] = {
          manifest: manifest,
          path: skill_dir,
        }
      rescue => e
        puts "[SkAgent] ERROR loading skill '#{File.basename(skill_dir)}': #{e.message}"
      end

      # --- Registry API ---

      def self.list
        @registry.map {|name, info|
          m = info[:manifest]
          {
            name: name,
            display_name: m['display_name'],
            description: m['description'],
            version: m['version'],
            license: m['license'],
            runtime: m['runtime'] || 'ruby',
            tags: m['tags'],
          }
        }
      end

      def self.get(name)
        @registry[name]
      end

      def self.readme(name)
        info = @registry[name]
        return nil unless info
        readme_path = File.join(info[:path], 'README.md')
        File.exist?(readme_path) ? File.read(readme_path) : nil
      end

      def self.skills_dir
        SKILLS_DIR.tr('\\', '/')
      end

      # --- Auto-generate SKILLS_INDEX.md ---

      def self.generate_index
        index_path = File.join(SKILLS_DIR, 'SKILLS_INDEX.md')

        ruby_skills = []
        agent_skills = []
        hybrid_skills = []

        @registry.each {|name, info|
          m = info[:manifest]
          runtime = m['runtime'] || 'ruby'
          entry = { name: name, manifest: m }
          case runtime
          when 'agent'  then agent_skills << entry
          when 'hybrid' then hybrid_skills << entry
          else               ruby_skills << entry
          end
        }

        lines = []
        lines << '# SkAgent Skills Index'
        lines << ''
        lines << "> Auto-generated by SkAgent v#{PLUGIN_VERSION} | #{Time.now.strftime('%Y-%m-%d %H:%M')}"
        lines << "> Total: #{@registry.size} skill(s)"
        lines << ''

        write_section(lines, 'Ruby Skills (run inside SketchUp)', ruby_skills)
        write_section(lines, 'Agent Skills (agent executes instructions)', agent_skills)
        write_section(lines, 'Hybrid Skills (Ruby + Agent)', hybrid_skills)

        File.write(index_path, lines.join("\n"))
      rescue => e
        puts "[SkAgent] Failed to generate SKILLS_INDEX: #{e.message}"
      end

      private

      def self.write_section(lines, title, skills)
        return if skills.empty?
        lines << "## #{title}"
        lines << ''
        skills.each {|s|
          m = s[:manifest]
          api_summary = (m['api'] || []).map {|a|
            params = (a['params'] || {}).keys.join(', ')
            "#{a['method']}(#{params})"
          }.join(' | ')

          lines << "### #{m['display_name']} (`#{s[:name]}`)"
          lines << m['description']
          lines << "- **Version:** #{m['version']} | **License:** #{m['license']} | **Tags:** #{(m['tags'] || []).join(', ')}"
          lines << "- **API:** #{api_summary}" unless api_summary.empty?
          lines << "- [README.md](#{s[:name]}/README.md)"
          lines << ''
        }
      end
    end
  end
end
